site_name: Backand Documentation
use_directory_urls: false
pages:
- ['index.md', 'Backand Documentation']
- ['getting_started/index.md', 'Getting Started', 'Introduction']
- ['getting_started/quick_reference/index.md', 'Getting Started', 'Quick Reference']
- ['getting_started/vanilla_sdk/index.md', 'Getting Started', 'Vanilla SDK']
- ['getting_started/sdk/index.md', 'Getting Started', 'Angular - Ionic 1 SDK']
- ['getting_started/sdk2/index.md', 'Getting Started', 'Angular - Ionic 2 SDK']
- ['getting_started/redux/index.md', 'Getting Started', 'Redux - React SDK']
- ['getting_started/objects/index.md', 'Getting Started', 'Objects']
- ['getting_started/queries/index.md', 'Getting Started', 'Queries']
- ['getting_started/crons/index.md', 'Getting Started', 'Background Jobs']
- ['getting_started/security_auth/index.md', 'Getting Started', 'Security & Auth']
- ['getting_started/hosting/index.md', 'Getting Started', 'Hosting']
- ['getting_started/log/index.md', 'Getting Started', 'Log']
- ['getting_started/settings/index.md', 'Getting Started', 'Settings']
- ['apidocs/index.md', 'API Documentation',  'Introduction']
- ['apidocs/security/index.md', 'API Documentation',  'Security Concepts']
- ['apidocs/files/index.md', 'API Documentation',  'Backand Storage']
- ['apidocs/realtime/index.md', 'API Documentation',  'Realtime Database Communication']
- ['apidocs/customactions/index.md', 'API Documentation',  'Custom Actions']
- ['apidocs/queries/index.md', 'API Documentation',  'Queries']
- ['apidocs/nosql_query_language/index.md', 'API Documentation',  'NOSQL Query Language']
- ['apidocs/apidescription/index.md', 'API Documentation',  'API Description']
- ['what_would_you_like_to_do/index.md', 'Common Use Cases', 'What would you like to do?']
- ['what_would_you_like_to_do/convert_new_sdk/index.md', 'Common Use Cases', 'Convert an older app to our serverless SDK']
- ['what_would_you_like_to_do/database/index.md', 'Common Use Cases', 'Database Setup & Configuration']
- ['what_would_you_like_to_do/rest/index.md', 'Common Use Cases', 'REST API Playground']
- ['what_would_you_like_to_do/security/index.md', 'Common Use Cases', 'Role-based Security Configuration']
- ['what_would_you_like_to_do/third_party/index.md', 'Common Use Cases', 'Integrating with Third Parties']
- ['what_would_you_like_to_do/geo/index.md', 'Common Use Cases', 'Geography Points']
- ['what_would_you_like_to_do/actions/index.md', 'Common Use Cases', 'Custom Actions']
- ['what_would_you_like_to_do/retrieve_data/index.md', 'Common Use Cases', 'Retrieving Data']
- ['what_would_you_like_to_do/bulk/index.md', 'Common Use Cases', 'Bulk operations']
- ['what_would_you_like_to_do/continuous_deployment/index.md', 'Common Use Cases', 'Continuous Deployment (CD) & Versions']
- ['what_would_you_like_to_do/i18n/index.md', 'Common Use Cases', 'Internationalization']
- ['what_would_you_like_to_do/ionic_creator/index.md', 'Common Use Cases', 'Integrating with Ionic Creator']
- ['scenarios/index.md', 'Scenarios',  'Introduction']
- ['scenarios/simple_web/index.md', 'Scenarios',  'Simple Web App with REST API']
- ['scenarios/ionic/index.md', 'Scenarios',  'Ionic with Backand']
- ['scenarios/simple_todo/index.md', 'Scenarios',  'Simple ToDo App']
- ['scenarios/todo_users/index.md', 'Scenarios',  'ToDo With Users']
- ['scenarios/fbuserinfo/index.md', 'Scenarios',  'Retrieving data from Facebook']
- ['scenarios/amazon/index.md', 'Scenarios', 'Amazon AWS and S3 Integration']
- ['scenarios/stripe/index.md', 'Scenarios', 'Stripe Integration']
- ['scenarios/mandrillapp/index.md', 'Scenarios', 'Mandrill']
- ['scenarios/mailgun/index.md', 'Scenarios', 'Mailgun']
- ['scenarios/send_grid/index.md', 'Scenarios', 'SendGrid']
- ['scenarios/PayPal/index.md', 'Scenarios', 'PayPal']
- ['scenarios/Segment/index.md', 'Scenarios', 'Segment.io']
- ['scenarios/twilio/index.md', 'Scenarios', 'Twilio']
- ['scenarios/netmera/index.md', 'Scenarios', 'Netmera']
- ['scenarios/pushwoosh/index.md', 'Scenarios', 'PushWoosh']
- ['scenarios/fbmessengerbot/index.md', 'Scenarios', 'Facebook Messenger Bot']
