site_name: Backand Documentation
use_directory_urls: false
pages:
- ['index.md', 'Backand Documentation']
- ['getting_started/index.md', 'Getting Started', 'Introduction']
- ['getting_started/quick_reference.md', 'Getting Started', 'Quick Reference']
- ['getting_started/sdk.md', 'Getting Started', 'Backand SDK']
- ['getting_started/objects.md', 'Getting Started', 'Objects']
- ['getting_started/queries.md', 'Getting Started', 'Queries']
- ['getting_started/security_auth.md', 'Getting Started', 'Security & Auth']
- ['getting_started/log.md', 'Getting Started', 'Log']
- ['getting_started/settings.md', 'Getting Started', 'Settings']
- ['getting_started/hosting.md', 'Getting Started', 'Hosting']
- ['apidocs/index.md', 'API Documentation',  'Introduction']
- ['apidocs/security.md', 'API Documentation',  'Security Concepts']
- ['apidocs/realtime.md', 'API Documentation',  'Realtime Database Communication']
- ['apidocs/customactions.md', 'API Documentation',  'Custom Actions']
- ['apidocs/queries.md', 'API Documentation',  'Queries']
- ['apidocs/nosql_query_language.md', 'API Documentation',  'NOSQL Query Language']
- ['apidocs/apidescription.md', 'API Documentation',  'API Description']
- ['what_would_you_like_to_do/index.md', 'Common Use Cases', 'What would you like to do?']
- ['what_would_you_like_to_do/database.md', 'Common Use Cases', 'Database Setup & Configuration']
- ['what_would_you_like_to_do/rest.md', 'Common Use Cases', 'REST API Playground']
- ['what_would_you_like_to_do/security.md', 'Common Use Cases', 'Role-based Security Configuration']
- ['what_would_you_like_to_do/third_party.md', 'Common Use Cases', 'Integrating with Third Parties']
- ['what_would_you_like_to_do/actions.md', 'Common Use Cases', 'Custom Actions']
- ['what_would_you_like_to_do/retrieve_data.md', 'Common Use Cases', 'Retrieving Data']
- ['what_would_you_like_to_do/i18n.md', 'Common Use Cases', 'Internationalization']
- ['scenarios/index.md', 'Scenarios',  'Introduction']
- ['scenarios/simple_web.md', 'Scenarios',  'Simple Web App with REST API']
- ['scenarios/ionic.md', 'Scenarios',  'Ionic with Backand']
- ['scenarios/simple_todo.md', 'Scenarios',  'Simple ToDo App']
- ['scenarios/todo_users.md', 'Scenarios',  'ToDo With Users']
- ['scenarios/amazon.md', 'Scenarios', 'Amazon AWS and S3 Integration']
- ['scenarios/stripe.md', 'Scenarios', 'Stripe Integration']
- ['scenarios/mandrillapp.md', 'Scenarios', 'Mandrillapp']
- ['scenarios/mailgun.md', 'Scenarios', 'Mailgun']
- ['scenarios/PayPal.md', 'Scenarios', 'PayPal']
- ['scenarios/Segment.md', 'Scenarios', 'Segment.io']
