site_name: Backand Documentation
use_directory_urls: false
pages:
<<<<<<< HEAD
- ['index.md', 'Introduction']
- ['security/authentication.md', 'Security Concepts', "Authentication"]
- ['security/signup.md', 'Security Concepts', "Sign Up"]
- ['security/removeuser.md', 'Security Concepts', "Remove user from the app"]
- ['security/anonymousaccess.md', 'Security Concepts', "Anonymous Access"]
- ['security/linkusers.md', 'Security Concepts', "Link your app's users with Backand's users"]
- ['security/roles.md', 'Security Concepts', "Roles & Security Templates"]
- ['customactions/index.md', 'Custom Actions']
- ['customactions/serverside.md', 'Custom Actions', 'Server Side Javascript Code']
- ['customactions/transactional.md', 'Custom Actions', 'Transactional database script']
- ['customactions/sendemail.md','Custom Actions','Send Email']
- ['queries/queries.md', 'Queries']
- ['apidescription/apidescription.md', 'API Description']
=======
- ['index.md', 'Backand Documentation']
- ['getting_started/index.md', 'Getting Started', 'Introduction']
- ['getting_started/quick_reference.md', 'Getting Started', 'Quick Reference']
- ['getting_started/objects.md', 'Getting Started', 'Objects']
- ['getting_started/queries.md', 'Getting Started', 'Queries']
- ['getting_started/security_auth.md', 'Getting Started', 'Security & Auth']
- ['getting_started/log.md', 'Getting Started', 'Log']
- ['getting_started/settings.md', 'Getting Started', 'Settings']
- ['what_would_you_like_to_do/index.md', 'Common Use Cases', 'What would you like to do?']
- ['what_would_you_like_to_do/database.md', 'Common Use Cases', 'Database Setup & Configuration']
- ['what_would_you_like_to_do/rest.md', 'Common Use Cases', 'REST API Playground']
- ['what_would_you_like_to_do/security.md', 'Common Use Cases', 'Role-based Security Configuration']
- ['what_would_you_like_to_do/actions.md', 'Common Use Cases', 'Custom Actions']
- ['scenarios/index.md', 'Scenarios',  'Introduction']
- ['scenarios/simple_web.md', 'Scenarios',  'Simple Web App with REST API']
- ['scenarios/ionic.md', 'Scenarios',  'Ionic with Backand']
- ['scenarios/simple_todo.md', 'Scenarios',  'Simple ToDo App']
- ['scenarios/todo_users.md', 'Scenarios',  'ToDo With Users']
- ['apidocs/index.md', 'API Documentation',  'Introduction']
- ['apidocs/security.md', 'API Documentation',  'Security Concepts']
- ['apidocs/customactions.md', 'API Documentation',  'Custom Actions']
- ['apidocs/queries.md', 'API Documentation',  'Queries']
- ['apidocs/apidescription.md', 'API Documentation',  'API Description']
>>>>>>> 0d30ce160c44227a107639ba74b7ef2af6d36aae
