site_name: Backand Documentation
use_directory_urls: false
pages:
- ['index.md', 'Introduction']
- ['security.md', 'Security Concepts']
- ['customactions.md', 'Custom Actions']
- ['queries.md', 'Queries']
- ['apidescription.md', 'API Description']