site_name: Backand Documentation
pages:
- ['index.md', 'Introduction']
- ['security.md', 'Security Concepts']
- ['custom-actions.md', 'Custom Actions']
- ['queries.md', 'Queries']
- ['api-description.md', 'API Description']