site_name: Backand Documentation
use_directory_urls: false
pages:
- ['index.md', 'Introduction']
- ['security/authentication.md', 'Security Concepts', "Authentication"]
- ['security/signup.md', 'Security Concepts', "Sign Up"]
- ['security/removeuser.md', 'Security Concepts', "Remove user from the app"]
- ['security/anonymousaccess.md', 'Security Concepts', "Anonymous Access"]
- ['security/linkusers.md', 'Security Concepts', "Link your app's users with Backand's users"]
- ['security/roles.md', 'Security Concepts', "Roles & Security Templates"]
- ['customactions/customactions.md', 'Custom Actions', 'Home']
- ['customactions/serverside.md', 'Custom Actions', 'Server Side Javascript Code']
- ['customactions/transactional.md', 'Custom Actions', 'Transactional database script']
- ['customactions/sendemail.md','Custom Actions','Send Email']
- ['queries.md', 'Queries']
- ['apidescription/security.md', 'Security & Authentication']
- ['apidescription/crud.md', 'REST API CRUD Operations']
- ['apidescription/custom.md', 'Custom Actions']
- ['apidescription/queries.md', 'Queries']
- ['apidescription/experience.md', 'Experience More']